Develop
GolubevConstantine/java-filmorate pull request #17
Opened 2024-07-23 11:37 UTC by GolubevConstantine

2024-07-26 00:05 UTC, vlolad requested changes
Привет!

В общем и целом - работа достойная, вы вообще большие молодцы, что реализовали такой крупный проект в команде с:

Глобально для финальных правок надо вот что поправить:
1. В readme или описание PR надо добавить, какие фичи вы выбрали для реализации. По коду и истории коммитов/PR, конечно, видно, но лучше всю историю проекта в одном месте оформлять)
2. Доработать кастомные ошибки, сейчас они по сути дублируются и не всегда информативны, собственно можно и хендлеры ошибок после этого упростить
3. В паре мест можно докрутить спринговые аннотации
4*. Можно упростить запросы к базе
Со звездочкой, потому что с ограничениями уникальности и CASCADE, возможно, сейчас будет сложно разобраться. Попробуйте реализовать (и помучать наставника), если остается время, но грубых ошибок в запросах сейчас почти нет
Но при добавлении лайков MERGE надо прикрутить)

Вроде ничего не забыл, если будут вопросы - меня можно найти в Пачке

Всем хорошей пятницы!

2024-07-26 00:05 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +@Data
Комментарий не для правок, а скорее на будущее
С сущностями, которые используются в БД, лучше не использовать некоторые ломбоковские аннотации. Не так критично, когда пишутся нативные запросы, но при работе с некоторыми библиотеками (например Hibernate) они ломают почти всё

Как альтернатива - отдельно прописывать @Getter, @Setter и прочие требуемые аннотации, избегая конфликтных
Подробнее можно тут почитать, но это вы будете ещё дальше проходить: https://habr.com/ru/companies/haulmont/articles/564682/

2024-07-26 00:05 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/exception/DirectorNotFoundException.java
> +public class DirectorNotFoundException extends RuntimeException {
Все NotFoundException можно либо объединить в один класс (предпочтительно), либо сделать один кастомный NFE и от него наследовать все подобные ошибки
Сейчас в проекте >5 разных ошибок, которые по сути об одном и по внутреннему содержанию дублируют друг друга)

Чтобы не было конфликтов с одноименными классами из спринга, можно общий класс назвать, например, DataNotFoundException. И ловить её в одном хэндлере, так как сообщения об ошибках всё равно будут разные

2024-07-26 00:05 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/exception/ReviewNotFoundException.java
> +public class ReviewNotFoundException extends RuntimeException {
См. комментарий к DirectorNotFoundException

2024-07-26 00:05 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +            throw new DirectorNotFoundException("Режиcсёр не найден.");
Надо доработать комментарии к ошибкам, добавить какой режиссер не найден
Например "Режиcсёр с id=N не найден."

Проще всего - через строку добавлять прямо в message ошибки при выбрасывании, но можно заморочиться и добавить доп. поле в ошибку, куда прокидывать атрибут, вызвавший ошибку. Вариантов много)

Пока рекомендую не усложнять и просто доработать сообщения

2024-07-26 00:05 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +            throw new DirectorNotFoundException("Режиcсёр не найден.");
И это, само собой, комментарий ко всем сообщениям об ошибках, где можно добавить атрибут в сообщение. Id, название фильма или что-то ещё

2024-07-26 00:05 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleDirectorNotFoundException(final DirectorNotFoundException e) {
Хнедлеры NotFoundException можно объединить, расписал в комментарии к DirectorNotFoundException

2024-07-26 00:05 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Удален фильм id {}", id);
Подобные логи лучше после выполнения удаления записывать. Может ошибка выскочить при проверке на существование пользователя

2024-07-26 00:05 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +                                 @RequestParam Optional<Integer> count) {
Лучше по максимуму использовать возможности спринга
Для аннотации RequestParam можно задать параметры required и defaultValue, фреймворк при отсутствии параметра сам подставит нужное значение. Не придётся создавать отдельную переменную и использовать Optional
Для примера с count: `@RequestParam(required = false, defaultValue = "10") Integer count`

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/bind/annotation/RequestParam.html

В FilmContoller, кстати, есть это, так что вы точно сможете и здесь реализовать)

2024-07-26 00:05 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/model/FeedEntry.java
> +public class FeedEntry {
Вот это очень хорошая реализация!

2024-07-26 00:05 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            sql += "WHERE sub.film_id IN (SELECT film_id FROM film_genres WHERE genre_id = ?) AND EXTRACT(YEAR FROM sub.releasedate) = ?";
Это уже со звёздочкой, если захочется совсем сильно рефакторить проект
Много где встречается подобный паттерн генерации строки для запроса через if - else if. Можно его упростить

Можно создать класс со статическими методами, которые бы добавляли либо дефолтные значения к строке (например, метод and() добавляет к строке "AND"), либо заданную строку (например, метод .add("EXTRACT(YEAR FROM sub.releasedate) = ?")

Если продумать условия вызовов этих методов, но можно будет избежать дублирования похожих строк

Опять же, это если совсем-совсем хочется, не обязательно) Подобную логику потом встретите в будущих проектах, если будете использовать JPA Specifications

2024-07-26 00:05 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        String sqlFilmGenres = "DELETE FROM FILM_GENRES WHERE film_id = ? ";
Лучше использовать CASCADE, чтобы при удалении фильма удалялись и связанные данные в лайках и жанрах. Сокращается до 1 запроса)
Попробуйте реализовать, если останется время до дедлайна

2024-07-26 00:05 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    public List<Film> findRecommendedFilms(int userId) {
Это хорошо придумано, но мне очень не хватило комментирования кода, долго разбирался)
Молодцы, что по сути в один запрос уместили логику

2024-07-26 00:05 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/dao/LikeBbStorage.java
> +        List<Map<String, Object>> queryForList = jdbcTemplate.queryForList(
Дополнительная проверка не нужна, вместо INSERT можно использовать MERGE. Надо поправить

Вариант сложнее - с добавлением ограничения в базу, сделать значения фильм-пользователь уникальными. В таком случае при попытке добавить ещё одно будет выбрасываться ошибка и не потребуется предварительная проверка

2024-07-26 00:05 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +        String sql = "DELETE FROM USERS WHERE USER_ID = ?";
Тут тоже можно использовать CASCADE для удаления зависимых данных, попробуйте реализовать

2024-07-26 00:05 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +public class Review {
Опционально кстати можно добавить интерфейсы, которые позволят менять логику валидации при выполнении разных операций
Например, для создания одни ограничения, для обновления - другие

https://reflectoring.io/bean-validation-with-spring-boot/#using-validation-groups-to-validate-objects-differently-for-different-use-cases
https://stackoverflow.com/questions/68680952/single-model-for-create-and-update-request-with-different-validation-strategy

Не конкретно для этой сущности пример, просто вспомнил на этом моменте)

2024-07-26 00:05 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    private void throwExceptionIfReviewNotFound(int id) {
По результату выполнения методы названы правильно, но лучше поменять нейминг на checkReviewExists и подобные. Опираемся на функционал метода, не на результат)

2024-07-26 05:48 UTC, GregSerbin commented on src/main/java/ru/yandex/practicum/filmorate/exception/DirectorNotFoundException.java
> +public class DirectorNotFoundException extends RuntimeException {
Исправил

2024-07-26 05:48 UTC, GregSerbin commented on src/main/java/ru/yandex/practicum/filmorate/exception/ReviewNotFoundException.java
> +public class ReviewNotFoundException extends RuntimeException {
Исправил

2024-07-26 05:48 UTC, GregSerbin commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +            throw new DirectorNotFoundException("Режиcсёр не найден.");
Исправил

2024-07-26 05:48 UTC, GregSerbin commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleDirectorNotFoundException(final DirectorNotFoundException e) {
Исправил

2024-07-26 05:49 UTC, GregSerbin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Удален фильм id {}", id);
Исправил

2024-07-26 05:59 UTC, GregSerbin commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +                                 @RequestParam Optional<Integer> count) {
Исправил

2024-07-26 06:08 UTC, GregSerbin commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        String sqlFilmGenres = "DELETE FROM FILM_GENRES WHERE film_id = ? ";
Исправил

2024-07-26 06:42 UTC, iGladkikh commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +        String sql = "DELETE FROM USERS WHERE USER_ID = ?";
Исправлено

2024-07-26 06:52 UTC, iGladkikh commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +@Data
Принято, спасибо!

2024-07-26 06:54 UTC, iGladkikh commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +public class Review {
Принято на будущее, спасибо!

2024-07-26 06:58 UTC, iGladkikh commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    private void throwExceptionIfReviewNotFound(int id) {
Исправлено

2024-07-26 07:10 UTC, iGladkikh commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            sql += "WHERE sub.film_id IN (SELECT film_id FROM film_genres WHERE genre_id = ?) AND EXTRACT(YEAR FROM sub.releasedate) = ?";
Приняли к сведению на будущее) Спасибо!

2024-07-26 07:36 UTC, iGladkikh commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    public List<Film> findRecommendedFilms(int userId) {
Код дополнен комментарием

2024-07-26 10:19 UTC, iGladkikh commented on src/main/java/ru/yandex/practicum/filmorate/dao/LikeBbStorage.java
> +        List<Map<String, Object>> queryForList = jdbcTemplate.queryForList(
Реализован вариант с уникальным ключом

2024-07-27 22:54 UTC, vlolad approved these changes
Привет!

Всё поправлено, молодцы!
Проект вообще замечательный, так как вы прощупали логику работы почти всех бэкенд приложений

Если после обучения надумаете собирать портфолио - можно взять текущие наработки и добавить в них ещё авторизацию через Spring Security, кэширование (рекомендую Caffeine Cache) и soft delete. С таким проектом собеседования пойдут лучше, по своему опыту говорю)

И самое главное на будущее, то что забыл в прошлой итерации - почти общепринято на один ПР/одну фичу отправлять один коммит. Так ветка не пухнет от мелких правок. Для этого используется amend commit, а если ПР уже создан - ещё force push в ветку, которая вливается. Но если уже запушили в dev, то изменения только через новый ПР
Это, по ощущениям, в 90% команд практикуется, так что берите на заметку)

Короче говоря, двигаемся дальше, диплом не за горами (￣^￣)ゞ

2024-07-27 22:54 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +                     LEFT JOIN directors AS d ON d.director_id = fd.director_id
Вижу, джоины освоены хорошо)

2024-07-27 22:54 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/dao/LikeBbStorage.java
> +            log.warn(e.getMessage());
В идеале ещё возвращать ошибку, которая бы отправлялась в ErrorHandler и клиенту
Иначе может быть непонятно, как обработан запрос

2024-07-27 22:54 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/dao/LikeBbStorage.java
> +            log.warn(e.getMessage());
И, по правде говоря, через MERGE было бы проще, тут я загнул с уникальностью записей)
Обычно когда есть несколько вариантов решения опираться надо на бизнес-требования. По моим ощущениям, если лайк уже есть, то можно ошибку не выводить и просто мержить изменения в базу (т.е. если лайка нет - он добавится, а если есть - ничего не изменится и это нормально для добавления лайка)

Но для практики - молодцы, что реализовали!

2024-07-29 06:22 UTC, merged