Add database
GolubevConstantine/java-filmorate pull request #7
Opened 2024-07-10 13:46 UTC by GolubevConstantine

2024-07-11 11:52 UTC, vlolad requested changes
Привет!

В целом всё хорошо, главное что с SQL работаешь уже уверенно)
Оставил несколько комментариев по API на улучшение, там немного правок, и будем приниматься

Хорошего дня!

2024-07-11 11:52 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
>      public ErrorResponse validateException(final MethodArgumentNotValidException e) {
В хэндлере обычно методы именуются как _handleException_, по имени ошибки
Например тут handleMethodArgumentNotValidException

2024-07-11 11:52 UTC, vlolad commented on src/main/resources/schema.sql
> +PRIMARY KEY(user_id, friend_id),
Лучше перенести после указания всех столбцов, перед внешними ключами. Как при создании likes

2024-07-11 11:52 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
>          return new ResponseEntity<>(e.getMessage(), HttpStatus.BAD_REQUEST);
Правильнее во всех методах возвращать ResponseEntity<>(), но т.к. у тебя в основном кастомный ErrorResponse возвращается, лучше и тут возвращать его)

Однородные задачи в коде должны решаться одинаково, иначе код становится путанный

2024-07-11 11:52 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreStorage.java
> +public interface GenreStorage {
Вполне можно тут оставить только findAll() и findById(), как у MPA

2024-07-11 13:44 UTC, GolubevConstantine commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreStorage.java
> +public interface GenreStorage {
Привет! findAllGenresByFilmID оставил т.к. при большом количестве жанров  и фильмов у приложения будет плохой перфоманс. Нам нужны не все жанры, а только жанры определенного фильма

2024-07-12 07:47 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreStorage.java
> +public interface GenreStorage {
Хорошо, это не ошибка)
Можно было бы решить проще эту проблему через join, но в этом проекте надо действительно по максимуму использовать все сервисы, так что принимаю

2024-07-12 07:48 UTC, vlolad approved these changes
Привет!

Все отлично, принимаю)

2024-07-15 15:41 UTC, merged